# .github/workflows/build-and-test.yml
name: Build and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore EasySave.sln
      - run: dotnet build EasySave.sln --configuration Release
      - run: dotnet test ./Tests/Unit-Tests/Unit-Tests.csproj --no-build --configuration Release
